// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCURk_0rzockKABZSm5pG6QChnOPtbsSz4',
    appId: '1:272950065400:web:bfe6b149c14be27426e30d',
    messagingSenderId: '272950065400',
    projectId: 'mindwave-5f797',
    authDomain: 'mindwave-5f797.firebaseapp.com',
    storageBucket: 'mindwave-5f797.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgul-hd-I1cjVj5siyLdi_6vnft_W-FU',
    appId: '1:272950065400:android:f35c23e2fb001dea26e30d',
    messagingSenderId: '272950065400',
    projectId: 'mindwave-5f797',
    storageBucket: 'mindwave-5f797.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGutMoNCQ2vty8AKpfggyivbE0qcJiDlI',
    appId: '1:272950065400:ios:0fcf7cecf729dd9826e30d',
    messagingSenderId: '272950065400',
    projectId: 'mindwave-5f797',
    storageBucket: 'mindwave-5f797.firebasestorage.app',
    iosBundleId: 'com.example.mindwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGutMoNCQ2vty8AKpfggyivbE0qcJiDlI',
    appId: '1:272950065400:ios:0fcf7cecf729dd9826e30d',
    messagingSenderId: '272950065400',
    projectId: 'mindwave-5f797',
    storageBucket: 'mindwave-5f797.firebasestorage.app',
    iosBundleId: 'com.example.mindwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCURk_0rzockKABZSm5pG6QChnOPtbsSz4',
    appId: '1:272950065400:web:c526b44d20e5ca4d26e30d',
    messagingSenderId: '272950065400',
    projectId: 'mindwave-5f797',
    authDomain: 'mindwave-5f797.firebaseapp.com',
    storageBucket: 'mindwave-5f797.firebasestorage.app',
  );

}