// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-c7rhLykB-WJ32Ozz2GF8WSlJOyk0aWQ',
    appId: '1:1015546170489:web:0e6374225efa5793c3d8a8',
    messagingSenderId: '1015546170489',
    projectId: 'dear-diary-88f96',
    authDomain: 'dear-diary-88f96.firebaseapp.com',
    storageBucket: 'dear-diary-88f96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWWneGjHBcnG4of2aM_9LxoRjlQaDxfo',
    appId: '1:1015546170489:android:ac9fbddda94efb7dc3d8a8',
    messagingSenderId: '1015546170489',
    projectId: 'dear-diary-88f96',
    storageBucket: 'dear-diary-88f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsXWgR6ghbxfE_SK9C4_XoEBPrDhAmIhQ',
    appId: '1:1015546170489:ios:c39877177b1a542fc3d8a8',
    messagingSenderId: '1015546170489',
    projectId: 'dear-diary-88f96',
    storageBucket: 'dear-diary-88f96.firebasestorage.app',
    iosClientId: '1015546170489-lueqbqcpv8tbgm97p44vh5cg947jrtqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsXWgR6ghbxfE_SK9C4_XoEBPrDhAmIhQ',
    appId: '1:1015546170489:ios:c39877177b1a542fc3d8a8',
    messagingSenderId: '1015546170489',
    projectId: 'dear-diary-88f96',
    storageBucket: 'dear-diary-88f96.firebasestorage.app',
    iosClientId: '1015546170489-lueqbqcpv8tbgm97p44vh5cg947jrtqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-c7rhLykB-WJ32Ozz2GF8WSlJOyk0aWQ',
    appId: '1:1015546170489:web:bb67c2b3ea42e5a7c3d8a8',
    messagingSenderId: '1015546170489',
    projectId: 'dear-diary-88f96',
    authDomain: 'dear-diary-88f96.firebaseapp.com',
    storageBucket: 'dear-diary-88f96.firebasestorage.app',
  );
}
